# coding: utf-8

"""
    demo

    this is a demo for device manager  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Interface(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'device_id': 'str',
        'interface_type': 'int',
        'ip': 'str'
    }

    attribute_map = {
        'id': 'id',
        'device_id': 'deviceId',
        'interface_type': 'interface_type',
        'ip': 'ip'
    }

    def __init__(self, id=None, device_id=None, interface_type=None, ip=None):  # noqa: E501
        """Interface - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._device_id = None
        self._interface_type = None
        self._ip = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if device_id is not None:
            self.device_id = device_id
        if interface_type is not None:
            self.interface_type = interface_type
        if ip is not None:
            self.ip = ip

    @property
    def id(self):
        """Gets the id of this Interface.  # noqa: E501


        :return: The id of this Interface.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Interface.


        :param id: The id of this Interface.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def device_id(self):
        """Gets the device_id of this Interface.  # noqa: E501


        :return: The device_id of this Interface.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this Interface.


        :param device_id: The device_id of this Interface.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def interface_type(self):
        """Gets the interface_type of this Interface.  # noqa: E501


        :return: The interface_type of this Interface.  # noqa: E501
        :rtype: int
        """
        return self._interface_type

    @interface_type.setter
    def interface_type(self, interface_type):
        """Sets the interface_type of this Interface.


        :param interface_type: The interface_type of this Interface.  # noqa: E501
        :type: int
        """

        self._interface_type = interface_type

    @property
    def ip(self):
        """Gets the ip of this Interface.  # noqa: E501


        :return: The ip of this Interface.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Interface.


        :param ip: The ip of this Interface.  # noqa: E501
        :type: str
        """

        self._ip = ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Interface, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Interface):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
