swagger: '2.0'
info:
  description: >-
    this is a demo for device manager
  version: 1.0.0
  title: demo
  termsOfService: 'http://localhost:8080/terms/'
tags:
  - name: Device
    description: network device model
  - name: Interface
    description: network interfaces for device model
schemes:
  - http
paths:
  /resmgr/dev:
    post:
      tags:
        - device
      summary: Add a new pet to the store
      description: ''
      operationId: addDevice
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Device'
      responses:
        '405':
          description: Invalid input
definitions:
  Device:
    type: object
    properties:
      id:
        type: integer
        format: int64
      esn:
        type: integer
        format: int64
      name:
        type: string
        format: int32
      type:
        type: integer
        format: int16
      status:
        type: integer
        format: int16
      interfaces:
        type: array
        items:
          $ref: '#/definitions/Interface'
  Interface:
    type: object
    properties:
      id:
        type: integer
        format: int64
      deviceId:
        type: string
        format: int64
      type:
        type: integer
        format: int16
      ip:
        type: string

